name: CI_resposta

# Controla quando o fluxo de trabalho será executado
on:
  # Aciona o fluxo de trabalho ao fazer push ou pull request para a branch master
  # push:
  #   branches: [ "master" ]
  # pull_request:
  #   branches: [ "master" ]

  # Permite executar este fluxo de trabalho manualmente na guia Actions
  workflow_dispatch:

# Um fluxo de trabalho é composto por um ou mais jobs que podem ser executados sequencialmente ou em paralelo
jobs:
  # Este fluxo de trabalho contém um único job chamado "test-lint"
  test-lint:
  
    # O tipo de runner em que o job será executado
    runs-on: ubuntu-latest



    # Os steps representam uma sequência de tarefas que serão executadas como parte do job
    steps:
      # Faz o checkout do seu repositório em $GITHUB_WORKSPACE, para que o job possa acessá-lo
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            EXERCICIO_CI_CD:
              - 'exercicio_ci_cd/resposta/**' 
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11' 

      - name: Instalar Poetry
        uses: snok/install-poetry@v1
        with:
          version: 2.1.1

      - name: Instalar Just
        uses: extractions/setup-just@v1

      - name: Instalar dependências
        run: poetry install

      - name: lint
        run: just lint
        shell: bash

      - name: testes
        run: just teste
        shell: bash
